### PR TITLE
.ply format fixed

### PR DESCRIPTION
**Pull request by Hexx2bin**
fixed the error with the .ply format that wasn´t let these files were read by some 3D editors

### CODE REVIEW

**Comment by Hexx2bin** [comment]
I had problems when I saved the PC in .ply format and then tryed to open the file with 3D programas for make a mesh based on the PC so I made some changes in the form that .ply format whas writed and this fix the problem

**Comment by MarekKowalski** [comment]
Thanks a lot for starting the PR Hexx2bin!
I'm in a bit of a rush now, I'll take a look at it in a couple of days.

**Comment by ChristopherRemde** [comment]
I can also confirm that this fix works and helped us solve our problems with importing the Pointclouds into other programs!

**Comment by MarekKowalski** [comment]
Thanks for confirming that this works Christopher.

**Pull request merged**
